spring.application.name=inventario
# 1. Direccion y nombre de la base de datos (Cambialo si tu base de datos se llama distinto)
spring.datasource.url=jdbc:mysql://localhost:3306/pasteleria_db?createDatabaseIfNotExist=true&serverTimezone=UTC

#Docker
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/pasteleria_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# 2. Tu usuario de MySQL (Por defecto suele ser root)
spring.datasource.username=Max

# 3. La contrasena que inventaste cuando instalamos MySQL (Ejemplo: admin123 o pasteles123)
spring.datasource.password=Maximo1234521

# 4. Driver de conexion
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 5. Configuracion de Hibernate para que cree las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
